'use client';
import {useState,useEffect,useRef} from 'react';
import Link from 'next/link';
import type {MediaSlot} from '../../lib/projects';
import type {MediaRecord,SiteSettings} from '../../lib/storage';
const allowed=['image/jpeg','image/png','image/webp','image/gif','image/avif','video/mp4','video/webm'];
type Placement={slot:string;media_id:string};
async function request(url:string,options?:RequestInit){const r=await fetch(url,options);if(!r.ok){let text=await r.text();try{text=JSON.parse(text).error||text}catch{}throw new Error(text||'Something went wrong. Please try again.')}return r.json() as Promise<{media:MediaRecord[];placements:Placement[]}>}
function bytes(n:number){return n<1024*1024?`${Math.ceil(n/1024)} KB`:`${(n/1024/1024).toFixed(1)} MB`}
export default function Studio({claimed,isOwner,displayName,projects,slots,initialSettings}:{claimed:boolean;isOwner:boolean;displayName:string;projects:{slug:string;title:string;number:string}[];slots:MediaSlot[];initialSettings:SiteSettings}){
 const [code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[media,setMedia]=useState<MediaRecord[]>([]),[placements,setPlacements]=useState<Placement[]>([]),[selected,setSelected]=useState(''),[project,setProject]=useState(projects[0].slug),[search,setSearch]=useState(''),[alt,setAlt]=useState(''),[confirmDelete,setConfirmDelete]=useState(false),[settings,setSettings]=useState(initialSettings),[loading,setLoading]=useState(isOwner),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(0);
 const input=useRef<HTMLInputElement>(null);
 async function refresh(){const data=await request('/api/studio/media');setMedia(data.media);setPlacements(data.placements)}
 useEffect(()=>{if(isOwner)refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[isOwner]);
 const item=media.find(m=>m.id===selected);const currentSlots=slots.filter(s=>s.projectSlug===project);
 useEffect(()=>{setAlt(item?.alt||'');setConfirmDelete(false)},[item?.id,item?.alt]);
 async function action(fn:()=>Promise<void>,message:string){setError('');setNotice('');setBusy(true);try{await fn();setNotice(message)}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 async function upload(files:FileList|null){if(!files?.length||busy||uploading)return;setError('');setNotice('');setUploading(true);const list=Array.from(files);let succeeded=0;try{for(let i=0;i<list.length;i++){const file=list[i];if(!allowed.includes(file.type))throw new Error(`${file.name}: use JPG, PNG, WebP, GIF, AVIF, MP4 or WebM.`);if(file.size>25*1024*1024||!file.size)throw new Error(`${file.name}: choose a non-empty file up to 25 MB.`);const data=await new Promise<{id:string}>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/studio/media');xhr.setRequestHeader('Content-Type',file.type);xhr.setRequestHeader('X-Filename',encodeURIComponent(file.name));xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(((i+e.loaded/e.total)/list.length)*100))};xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)resolve(JSON.parse(xhr.responseText));else reject(new Error(xhr.responseText||'Upload failed'))};xhr.onerror=()=>reject(new Error('The connection was interrupted. Please try again.'));xhr.send(file)});succeeded++;setSelected(data.id)}setNotice(`${succeeded} ${succeeded===1?'file uploaded':'files uploaded'}. Choose a project position to add it to the site.`)}catch(e){setError(`${e instanceof Error?e.message:'Upload failed'}${succeeded?` ${succeeded} earlier file(s) were saved.`:''}`)}finally{await refresh().catch(()=>{});setUploading(false);setProgress(0);if(input.current)input.current.value=''}}
 const disabled=busy||uploading;
 return <section className="wrap studio"><div className="studio-heading"><div><p className="eyebrow">— Private workspace</p><h1>Media <em>studio.</em></h1></div><Link href="/" className="text-link">View portfolio ↗</Link></div><p className="studio-intro">Upload your images and videos. Place them in the portfolio when they’re ready.</p>
 <div className="studio-account"><span>Signed in as {displayName}</span><a href="/signout-with-chatgpt?return_to=%2F">Sign out</a></div>
 {error&&<div className="status-banner error-banner" role="alert">{error}</div>}{notice&&<div className="status-banner" role="status">{notice}</div>}
 {!isOwner?(<div className="studio-setup"><p className="eyebrow">{claimed?'Restricted access':'One-time owner setup'}</p><h2>{claimed?'This studio belongs to another account.':'Connect your account to this portfolio.'}</h2><p>{claimed?'Sign in with the account used to set up this media studio.':'Enter the private setup code supplied with your site. After this one-time step, your ChatGPT account is the only account that can manage media.'}</p>{!claimed&&<form onSubmit={e=>{e.preventDefault();action(async()=>{await request('/api/studio/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});window.location.reload()},'Studio connected.')}}><label htmlFor="setup-code">Private setup code</label><input id="setup-code" type="password" value={code} onChange={e=>setCode(e.target.value)} autoComplete="off" required/><button className="button" disabled={busy||!code}>Connect my account ↗</button></form>}</div>):<>
 <div className="studio-stats"><div><strong>{media.length}</strong><span>Uploaded files</span></div><div><strong>{placements.length} / {slots.length}</strong><span>Positions filled</span></div><div><strong>{projects.length}</strong><span>Project collections</span></div></div>
 <div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!disabled)upload(e.dataTransfer.files)}}><span className="upload-mark" aria-hidden="true">↑</span><div><h2>Make room for the work.</h2><p>Drop images or videos here, or browse your files.</p><small>JPG, PNG, WebP, GIF, AVIF, MP4, WebM · 25 MB per file</small></div><button className="button" disabled={disabled} onClick={()=>input.current?.click()}>{uploading?`Uploading ${progress}%`:'Upload media ↑'}</button><input ref={input} aria-label="Upload portfolio media" type="file" accept={allowed.join(',')} multiple hidden onChange={e=>upload(e.target.files)}/>{uploading&&<progress value={progress} max={100} aria-label="Upload progress"/>}</div>
 <p className="studio-note">Uploads stay private until you assign them to a position. Assigned files are visible to anyone who can view the portfolio. Changes to positions appear after refreshing the portfolio.</p>
 <div className="studio-workspace"><div className="library"><div className="library-heading"><h2>Your library</h2><label><span className="sr-only">Search media</span><input placeholder="Search filenames…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{loading?<p className="empty-state">Loading your library…</p>:media.length===0?<div className="library-empty"><span>＋</span><h3>Your work goes here.</h3><p>The site uses placeholders until you upload and assign media.</p></div>:<div className="media-grid">{media.filter(m=>m.filename.toLowerCase().includes(search.toLowerCase())).map(m=><button key={m.id} className={`media-tile ${selected===m.id?'is-selected':''}`} aria-pressed={selected===m.id} onClick={()=>setSelected(m.id)}><div className="media-tile-preview">{m.mime.startsWith('video/')?<><video src={`/api/media/${m.id}`} muted preload="metadata"/><span className="video-badge">Video ▷</span></>:<img src={`/api/media/${m.id}`} alt={m.alt||m.filename} loading="lazy"/>}</div><strong>{m.filename}</strong><span>{bytes(m.bytes)} · {placements.filter(p=>p.media_id===m.id).length?'Assigned':'Unassigned'}</span></button>)}</div>}
 {item&&<div className="file-details"><div className="file-details-heading"><h3>{item.filename}</h3><button className="text-button" onClick={()=>setSelected('')}>Close ×</button></div>{item.mime.startsWith('video/')&&<video className="selected-video" src={`/api/media/${item.id}`} controls preload="metadata"/>}<p>{bytes(item.bytes)} · {item.mime} · Added {new Date(item.created_at).toLocaleDateString()}</p><label htmlFor="media-alt">Description / alternative text</label><textarea id="media-alt" maxLength={400} value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Describe what the image or video shows." rows={3}/><div className="file-actions"><button className="button secondary" disabled={disabled} onClick={()=>action(async()=>{await request('/api/studio/media',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,alt})});await refresh()},'Description saved.')}>Save description</button><button className="text-button danger" disabled={disabled} onClick={()=>setConfirmDelete(true)}>Delete file</button></div>{confirmDelete&&<div className="delete-confirm" role="alert"><p>Delete “{item.filename}”? This removes the stored file and restores placeholders in all {placements.filter(p=>p.media_id===item.id).length} assigned positions.</p><button className="button danger-button" disabled={disabled} onClick={()=>action(async()=>{await request('/api/studio/media',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id})});setSelected('');await refresh()},'File deleted. Its positions now use placeholders.')}>Delete permanently</button><button className="text-button" onClick={()=>setConfirmDelete(false)}>Cancel</button></div>}</div>}
 </div><aside className="placement-panel"><p className="eyebrow">— Place your media</p><h2>Project positions</h2><p>Choose a project, then select a file for each position. Reuse a file in as many positions as you need.</p><label htmlFor="project-select">Project</label><select id="project-select" value={project} onChange={e=>setProject(e.target.value)}>{projects.map(p=><option key={p.slug} value={p.slug}>{p.number} / {p.title}</option>)}</select><Link className="text-link" href={`/work/${project}`} target="_blank">View this case study ↗</Link><div className="slot-list">{currentSlots.map(s=>{const binding=placements.find(p=>p.slot===s.key);const m=media.find(m=>m.id===binding?.media_id);return <div className="slot-control" key={s.key}><label htmlFor={`slot-${s.key}`}>{s.label}</label><select id={`slot-${s.key}`} value={m?.id||''} disabled={disabled} onChange={e=>{const mediaId=e.target.value||null;action(async()=>{await request('/api/studio/placements',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({slot:s.key,mediaId})});await refresh()},mediaId?'Position updated. Refresh the portfolio to see it.':'Placeholder restored.')}}><option value="">Placeholder — no media assigned</option>{media.map(m=><option key={m.id} value={m.id}>{m.mime.startsWith('video/')?'Video: ':''}{m.filename}</option>)}</select><span className={m?'slot-filled':'slot-empty'}>{m?'● Assigned':'○ Placeholder'}</span></div>})}</div></aside></div>
 <section className="studio-settings"><div><p className="eyebrow">— Site details</p><h2>A way to reach you.</h2><p>Add your confirmed contact details here. Empty fields stay hidden on the contact page.</p></div><form onSubmit={e=>{e.preventDefault();action(async()=>{await request('/api/studio/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)})},'Contact details saved.')}}><label htmlFor="contact-email">Public contact email</label><input id="contact-email" type="email" maxLength={254} value={settings.contact_email} onChange={e=>setSettings({...settings,contact_email:e.target.value})} placeholder="you@example.com"/><label htmlFor="location">Location / availability</label><input id="location" maxLength={120} value={settings.location} onChange={e=>setSettings({...settings,location:e.target.value})} placeholder="Your location or working availability"/><label htmlFor="linkedin">LinkedIn profile</label><input id="linkedin" type="url" maxLength={500} value={settings.linkedin} onChange={e=>setSettings({...settings,linkedin:e.target.value})} placeholder="https://www.linkedin.com/in/…"/><button className="button" disabled={disabled}>Save contact details ↗</button></form></section>
 </>}
 </section>;
}
