import type { Metadata } from 'next';
import Link from '../../components/SiteLink';
import {notFound} from 'next/navigation';
import {type Section} from '../../../lib/projects';
import {getContent} from '../../../lib/content';
import {ProseCopy as Prose} from '../../components/Copy';
import {mediaMap,type MediaMap} from '../../../lib/storage';
import Media from '../../components/Media';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const slug=(await params).slug;const p=(await getContent()).projects.find(p=>p.slug===slug);if(!p)return {title:'Project not found'};return {title:p.title,description:p.thesis,openGraph:{title:p.title,description:p.thesis,type:'article',images:[]},twitter:{card:'summary',title:p.title,description:p.thesis,images:[]}}}
function CaseSection({s,slug,projectId,map,text}:{s:Section;slug:string;projectId:string;map:MediaMap;text:(id:string)=>string}){
 const dark=s.background==='dark'||s.type==='dark_statement';const slot=(n=0)=>`project.${projectId}.${s.content_id}.${s.media_slots[n]}`;
 if(s.type==='pull_quote')return <section id={s.content_id} className={`case-section quote-section ${dark?'dark':''}`}><div className="wrap"><p className="eyebrow">{s.narrative_stage}</p><blockquote><span>“</span>{s.quote}<span>”</span></blockquote>{s.quote_attribution&&<p className="quote-attribution">{s.quote_attribution}</p>}</div></section>;
 if(s.type==='metrics')return <section id={s.content_id} className="case-section dark"><div className="wrap"><p className="eyebrow">{s.narrative_stage}</p><h2 className="case-section-title">{s.heading}</h2><div className="metrics">{s.metrics?.map(m=><div key={m.label}><strong>{m.value}</strong><span className="eyebrow">{m.label}</span></div>)}</div>{slug==='kryptek-paid-media-system'&&<p className="metric-note">{text("project.kryptek_paid_media.outcome.attribution")}</p>}</div></section>;
 if(['split_text_image','text_image'].includes(s.type))return <section id={s.content_id} className={`case-section ${dark?'dark':''}`}><div className="wrap"><p className="eyebrow">{s.narrative_stage}</p><div className={`case-split ${s.layout==='right'?'image-first':''}`}><div><h2 className="case-section-title">{s.heading}</h2><Prose text={s.body}/></div><Media slot={slot()} map={map} label={s.heading||'Project detail'} className="portrait" controls/></div></div></section>;
 if(['gallery','diptych','full_image','full_visual','video'].includes(s.type))return <section id={s.content_id} className={`case-section ${dark?'dark':''}`}><div className="wrap"><p className="eyebrow">{s.narrative_stage}</p><div className="case-gallery-heading"><h2 className="case-section-title">{s.heading}</h2>{s.body&&<Prose text={s.body}/>}</div><div className={['gallery','diptych'].includes(s.type)?'case-gallery':'case-visual'}>{(['gallery','diptych'].includes(s.type)?[0,1,2]:[0]).map(n=><Media key={n} slot={slot(n)} map={map} label={`${s.narrative_stage||'Project'} / ${String(n+1).padStart(2,'0')}`} className={['gallery','diptych'].includes(s.type)?'portrait':'wide'} controls kind={s.type==='video'||slug==='the-public-standard'?'video':'image / video'}/>)}</div></div></section>;
 return <section id={s.content_id} className={`case-section ${dark?'dark':''}`}><div className="wrap case-copy-grid"><p className="eyebrow">{s.narrative_stage}</p><div><h2 className="case-section-title">{s.heading}</h2><Prose text={s.body}/></div></div></section>;
}
export default async function CaseStudy({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const {projects,text}=await getContent();const p=projects.find(p=>p.slug===slug);if(!p)notFound();const map=await mediaMap();const i=projects.indexOf(p);const prev=projects[(i+projects.length-1)%projects.length],next=projects[(i+1)%projects.length];
 return <article><section className="wrap page-opening case-opening"><p className="eyebrow">— {p.project_number} / {p.strategic_intent} · {p.year}{p.slug==='the-public-standard'?` · ${text('project.public_standard.opening.status_label')}`:''}</p><div className="case-title-grid"><h1>{p.title}</h1><div><p className="case-subtitle">{p.subtitle}</p><p className="eyebrow">{p.client} · {p.year}</p></div></div><div className="case-intro"><h2>{p.thesis}</h2><Prose text={p.summary}/></div><dl className="project-facts"><div><dt>{text("global.project.client_label")}</dt><dd>{p.client}</dd></div><div><dt>{text("global.project.year_label")}</dt><dd>{p.year}</dd></div><div><dt>{text("global.project.role_label")}</dt><dd>{p.role.join(', ')}</dd></div><div><dt>{text("global.project.disciplines_label")}</dt><dd>{p.discipline_tags.join(', ')}</dd></div></dl></section><div className="wrap case-cover"><Media map={map} slot={`project.${p.content_id}.opening.hero`} label={`${p.title} / Cover`} className="cinematic" controls/></div>{p.content_sections.map((s,n)=><CaseSection key={s.content_id} s={s} slug={slug} projectId={p.content_id} map={map} text={text}/>)}<section className="case-section dark"><div className="wrap"><p className="eyebrow">{text("global.project.continue_label")}</p>{projects.length>1&&<div className="next-projects"><Link href={`/work/${prev.slug}`}><span className="eyebrow">{text("global.project.previous_label")}</span><h2>{prev.title}</h2></Link><Link href={`/work/${next.slug}`}><span className="eyebrow">{text("global.project.next_label")}</span><h2>{next.title}</h2></Link></div>}{projects.filter(r=>p.related_project_ids.includes(r.content_id)&&r.content_id!==p.content_id).map(r=><div key={r.content_id} className="back-index"><p className="eyebrow">{text("global.project.related_label")}</p><Link className="text-link" href={`/work/${r.slug}`}>{r.title} ↗</Link></div>)}<Link className="text-link back-index" href="/work">{text("global.project.index_label")}</Link></div></section></article>;
}
