// Permanent semantic keys; labels and copy may change without changing identity.
export const siteCopy:Record<string,string>={
'global.navigation.name':'Austin Lester','global.navigation.index.label':'Index','global.navigation.index.destination':'/work','global.navigation.about.label':'About','global.navigation.about.destination':'/about','global.navigation.contact.label':'Contact','global.navigation.contact.destination':'/contact',
'global.footer.eyebrow':'— Contact','global.footer.headline':'Let’s make it matter','global.footer.destination':'/contact','global.footer.body':'Strategy. Direction. Design.\nFrom the problem to the outcome.','global.footer.copyright':'© 2026 Austin Lester','global.footer.studio.label':'Media studio ↗',
'home.hero.eyebrow':'— Portfolio / Creative Direction','home.hero.year':'2026','home.hero.sequence_label':'Selected Work','home.hero.headline':'I identify problems, *develop ideas*, and turn strategy into tangible outcomes.','home.hero.intro':'Austin Lester — multidisciplinary creative leader across strategy, creative direction, design, and technology.','home.hero.primary_cta.label':'Selected work ↓','home.hero.primary_cta.destination':'/#selected-work',
'home.selected_work.eyebrow':'— Selected Work','home.selected_work.heading':'Case studies, in sequence','home.selected_work.index_cta.label':'Full index ↗','home.selected_work.index_cta.destination':'/work','home.selected_work.view_label':'View case study ↗','home.intent.eyebrow':'— Browse by intent','home.approach.eyebrow':'— Approach','home.approach.heading':'Working across strategy, creative direction, design, and technology — from the problem to the executed outcome.','home.approach.cta.label':'More about Austin ↗','home.approach.cta.destination':'/about',
'work.opening.eyebrow':'— Work / Index','work.opening.heading':'Project Index','work.opening.body':'Selected work across strategy, creative direction, design, storytelling, and technology. Organized by the problem addressed and the outcome pursued.','work.opening.count_label':'projects','work.filters.all_label':'All','work.index.empty_message':'No projects in this category yet.',
'about.opening.eyebrow':'— About / Austin Lester','about.opening.headline':'From the problem\nto the *outcome.*','about.opening.positioning':'Multidisciplinary creative leader across strategy, creative direction, design, and technology.','about.opening.stages':'Understand / Define / Direct / Build','about.perspective.eyebrow':'— Perspective','about.perspective.heading':'Working across disciplines.\nThinking about the whole.','about.perspective.body':'I identify problems, develop ideas, and turn strategy into tangible outcomes. My work connects brand and narrative strategy with creative direction, design, photography, film, and technology.\n\nSelected projects span identity systems, ecommerce experiences, content production, campaigns, editorial design, and interactive 3D. Across those disciplines, the focus stays on the problem being addressed and the outcome being pursued.','about.perspective.cta.label':'Explore the work ↗','about.perspective.cta.destination':'/work','about.approach.eyebrow':'— Approach',
'about.approach.understand.heading':'Understand','about.approach.understand.description':'Immerse in the problem, audience, and context before making.','about.approach.define.heading':'Define','about.approach.define.description':'Establish the strategy, framing, and direction.','about.approach.direct.heading':'Direct','about.approach.direct.description':'Lead creative direction, art direction, and craft.','about.approach.build.heading':'Build','about.approach.build.description':'Execute and produce the work across disciplines.',
'about.capabilities.eyebrow':'— Capabilities','about.capabilities.strategy.heading':'Strategy','about.capabilities.strategy.items':'Brand & narrative strategy\nPositioning\nResearch & insight','about.capabilities.creative_direction.heading':'Creative Direction','about.capabilities.creative_direction.items':'Creative direction\nArt direction\nCampaign development','about.capabilities.brand_narrative.heading':'Brand & Narrative','about.capabilities.brand_narrative.items':'Brand identity\nVoice & messaging\nStorytelling','about.capabilities.design.heading':'Design','about.capabilities.design.items':'Design systems\nEditorial design\nTypography','about.capabilities.photography_film.heading':'Photography & Film','about.capabilities.photography_film.items':'Photography direction\nFilm & motion\nProduction','about.capabilities.digital_technology.heading':'Digital & Technology','about.capabilities.digital_technology.items':'Digital experiences\n3D & creative technology\nInteraction design',
'contact.opening.eyebrow':'— Contact','contact.opening.headline':'Start a\n*conversation.*','contact.opening.body':'For projects across strategy, creative direction, design, and technology.','contact.direct.eyebrow':'— Direct','contact.direct.email':'','contact.direct.location':'','contact.direct.linkedin':'','contact.direct.linkedin_label':'LinkedIn ↗','contact.direct.pending_heading':'Contact details coming soon.','contact.direct.pending_body':'This portfolio is being prepared. A direct email link will appear here when the contact details are added.','contact.navigation.work.label':'← Explore the work','contact.navigation.work.destination':'/work',
'global.project.client_label':'Client','global.project.year_label':'Year','global.project.role_label':'Role','global.project.disciplines_label':'Disciplines','global.project.continue_label':'— Continue','global.project.previous_label':'← Previous project','global.project.next_label':'Next project ↗','global.project.related_label':'— Related','global.project.index_label':'Back to index ↗',
'project.public_standard.opening.status_label':'Film concept','project.kryptek_paid_media.outcome.attribution':'Campaign results reflect the combined contribution of creative, offers, media strategy, budget, landing experience, and campaign management. Paid-media execution and reporting: First Pier.'};
export const approachKeys=['understand','define','direct','build'];
export const capabilityKeys=['strategy','creative_direction','brand_narrative','design','photography_film','digital_technology'];
