// Permanent semantic keys; labels and copy may change without changing identity.
export const siteCopy:Record<string,string>={
'global.navigation.name':'Austin Lester','global.navigation.index.label':'Index','global.navigation.index.destination':'/work','global.navigation.about.label':'About','global.navigation.about.destination':'/about','global.navigation.contact.label':'Contact','global.navigation.contact.destination':'/contact',
'global.footer.eyebrow':'— Contact','global.footer.headline':'Let’s make it matter','global.footer.destination':'/contact','global.footer.body':'Strategy. Direction. Design.\nFrom the problem to the outcome.','global.footer.copyright':'© 2026 Austin Lester','global.footer.studio.label':'Media studio →',
'home.hero.eyebrow':'— Portfolio / Creative Direction','home.hero.year':'2026','home.hero.sequence_label':'Selected Work','home.hero.headline':'I identify problems, *develop ideas*, and turn strategy into tangible outcomes.','home.hero.intro':'Austin Lester — multidisciplinary creative leader across strategy, creative direction, design, and technology.','home.hero.primary_cta.label':'Selected work ↓','home.hero.primary_cta.destination':'/#selected-work',
'home.selected_work.eyebrow':'— Selected Work','home.selected_work.heading':'Case studies, in sequence','home.selected_work.index_cta.label':'Full index →','home.selected_work.index_cta.destination':'/work','home.selected_work.view_label':'View case study →','home.intent.eyebrow':'— Browse by intent','home.approach.eyebrow':'— Approach','home.approach.heading':'Working across strategy, creative direction, design, and technology — from the problem to the executed outcome.','home.approach.cta.label':'More about Austin →','home.approach.cta.destination':'/about',
'work.opening.eyebrow':'— Work / Index','work.opening.heading':'Project Index','work.opening.body':'Selected work across strategy, creative direction, design, storytelling, and technology. Organized by the problem addressed and the outcome pursued.','work.opening.count_label':'projects','work.filters.all_label':'All','work.index.empty_message':'No projects in this category yet.',
'about.opening.eyebrow':'— About / Austin Lester','about.opening.headline':'From the problem\nto the *outcome.*','about.opening.positioning':'Multidisciplinary creative leader across strategy, creative direction, design, and technology.','about.opening.stages':'Understand / Define / Direct / Build','about.perspective.eyebrow':'— Perspective','about.perspective.heading':'Working across disciplines.\nThinking about the whole.','about.perspective.body':'I identify problems, develop ideas, and turn strategy into tangible outcomes. My work connects brand and narrative strategy with creative direction, design, photography, film, and technology.\n\nSelected projects span identity systems, ecommerce experiences, content production, campaigns, editorial design, and interactive 3D. Across those disciplines, the focus stays on the problem being addressed and the outcome being pursued.','about.perspective.cta.label':'Explore the work →','about.perspective.cta.destination':'/work','about.approach.eyebrow':'— Approach',
'about.approach.understand.heading':'Understand','about.approach.understand.description':'Immerse in the problem, audience, and context before making.','about.approach.define.heading':'Define','about.approach.define.description':'Establish the strategy, framing, and direction.','about.approach.direct.heading':'Direct','about.approach.direct.description':'Lead creative direction, art direction, and craft.','about.approach.build.heading':'Build','about.approach.build.description':'Execute and produce the work across disciplines.',
'about.capabilities.eyebrow':'— Capabilities','about.capabilities.strategy.heading':'Strategy','about.capabilities.strategy.items':'Brand & narrative strategy\nPositioning\nResearch & insight','about.capabilities.creative_direction.heading':'Creative Direction','about.capabilities.creative_direction.items':'Creative direction\nArt direction\nCampaign development','about.capabilities.brand_narrative.heading':'Brand & Narrative','about.capabilities.brand_narrative.items':'Brand identity\nVoice & messaging\nStorytelling','about.capabilities.design.heading':'Design','about.capabilities.design.items':'Design systems\nEditorial design\nTypography','about.capabilities.photography_film.heading':'Photography & Film','about.capabilities.photography_film.items':'Photography direction\nFilm & motion\nProduction','about.capabilities.digital_technology.heading':'Digital & Technology','about.capabilities.digital_technology.items':'Digital experiences\n3D & creative technology\nInteraction design',
'about.testimonials.eyebrow':'— Testimonials','about.testimonials.shawn_herald.quote':'Austin has a rare ability to look beyond the immediate creative request and understand the larger problem we are actually trying to solve. He asks the right questions, challenges assumptions when necessary, and brings a level of thought to the work that makes the final result feel deliberate rather than simply well designed. He can move comfortably between strategy and execution, which made him an incredibly valuable creative partner.','about.testimonials.shawn_herald.name':'Shawn Herald','about.testimonials.shawn_herald.role':'Marketing Director','about.testimonials.shawn_herald.organization':'Bergara',
'about.testimonials.greg_williams.quote':'I have had the pleasure of working with Austin on various levels and within various projects and settings since 2020. In each of my experiences, I have been pleased and impressed with his quality of work in regard to his photography, videography and general creative skills, as well as his professional conduct being responsive, respectful, and thorough. I was particularly impressed with Austin\'s ability to understand the limited strategic creative direction given and apply the appropriate tactics to achieve our intended objectives without requiring extensive input or feedback from our team. His ability to provide quality work with little support and direction was impressive and extremely valuable. I highly recommend his services, not only for a premium quality product, but reliable and efficient communication and delivery.','about.testimonials.greg_williams.name':'Greg Williams','about.testimonials.greg_williams.role':'CEO','about.testimonials.greg_williams.organization':'Eberlestock',
'about.testimonials.bradley_farris.quote':'What impressed me most about working with Austin was his ability to bring clarity to projects that initially felt complicated or undefined. He could take a loose collection of ideas, business objectives, and creative references and turn them into a direction everyone understood and could get behind. The quality of the work was excellent, but the thinking behind it was what really separated him.','about.testimonials.bradley_farris.name':'Bradley Farris','about.testimonials.bradley_farris.role':'VP of Brand','about.testimonials.bradley_farris.organization':'CZ Firearms',
'about.testimonials.clint_easley.quote':'First off, Austin is the man! If you want someone that is genuine, honest, humble, efficient, an excellent listener, and phenomenal at what they do, then there\'s no more need to keep shopping around. Austin will absolutely crush it for you!!! I have owned a media company for the past 6 years and have been in the film & TV production industry for over 16 years and can tell you right now, that he is an extremely difficult talent to find. Everything he touches turns to gold, and he\'ll never take the credit, so this is my opportunity to do that for him. You\'re in excellent hands! This guy is not afraid to work, and is 100% passion driven which means he puts his heart into it and will go above and beyond for you! Thank you for all you do my friend, and looking forward to many future projects together!','about.testimonials.clint_easley.name':'Clint Easley','about.testimonials.clint_easley.role':'CEO','about.testimonials.clint_easley.organization':'REVOL Entertainment',
'about.testimonials.mark_miller.quote':'Austin is one of those creatives you can give a difficult problem to and trust that he will figure out what the work actually needs. Whether that means a new graphic, a photography shoot, a short film, a better landing page, or a full on campaign! He isn\'t afraid to suggest or just do something completely outside the original brief if he thinks it will add benefit to the result. He approaches it with the same level of care and ownership as if it were his company. He is thoughtful, resourceful, and exceptionally good at connecting the larger idea to the details that make it work.','about.testimonials.mark_miller.name':'Mark Miller','about.testimonials.mark_miller.role':'Founder & CEO','about.testimonials.mark_miller.organization':'Winfield Watch Company',
'about.selected_clients.eyebrow':'— Selected Clients',
'contact.opening.eyebrow':'— Contact','contact.opening.headline':'Start a\n*conversation.*','contact.opening.body':'For projects across strategy, creative direction, design, and technology.','contact.direct.eyebrow':'— Direct','contact.direct.email':'austinlesterstudio@gmail.com','contact.direct.location':'','contact.direct.linkedin':'','contact.direct.linkedin_label':'LinkedIn →','contact.direct.pending_heading':'Contact details coming soon.','contact.direct.pending_body':'This portfolio is being prepared. A direct email link will appear here when the contact details are added.','contact.navigation.work.label':'← Explore the work','contact.navigation.work.destination':'/work',
'global.project.client_label':'Client','global.project.year_label':'Year','global.project.role_label':'Role','global.project.disciplines_label':'Disciplines','global.project.continue_label':'— Continue','global.project.previous_label':'← Previous project','global.project.next_label':'Next project →','global.project.related_label':'— Related','global.project.index_label':'← Back to index',
'project.public_standard.opening.status_label':'Film concept','project.kryptek_paid_media.outcome.attribution':'Campaign results reflect the combined contribution of creative, offers, media strategy, budget, landing experience, and campaign management. Paid-media execution and reporting: First Pier.'};
export const approachKeys=['understand','define','direct','build'];
export const capabilityKeys=['strategy','creative_direction','brand_narrative','design','photography_film','digital_technology'];
