import type {Metadata} from 'next';
import Link from '../components/SiteLink';
import {getContent} from '../../lib/content';
import {approachKeys,capabilityKeys} from '../../content/site-copy';
import {clientLogos,resolveTestimonials} from '../../content/about-social-proof';
import {InlineCopy,ProseCopy} from '../components/Copy';
import ClientLogoWall from '../components/ClientLogoWall';
import TestimonialSlider from '../components/interactions/TestimonialSlider';
export const metadata:Metadata={title:'About',description:'Austin Lester — multidisciplinary creative leader across strategy, creative direction, design, and technology.',alternates:{canonical:'/about'},openGraph:{url:'/about'}};
export default async function About(){const {text}=await getContent();const capabilities=capabilityKeys.map(k=>[text(`about.capabilities.${k}.heading`),...text(`about.capabilities.${k}.items`).split("\n")]);const testimonials=resolveTestimonials(text);return <div className="about-page"><section className="about-wrap page-opening"><p className="eyebrow">{text("about.opening.eyebrow")}</p><h1><InlineCopy text={text("about.opening.headline")}/></h1><div className="opening-bottom"><p>{text("about.opening.positioning")}</p><span className="eyebrow">{text("about.opening.stages")}</span></div></section><section className="case-section"><div className="about-wrap case-copy-grid"><p className="eyebrow">{text("about.perspective.eyebrow")}</p><div><h2 className="case-section-title"><InlineCopy text={text("about.perspective.heading")}/></h2><ProseCopy text={text("about.perspective.body")}/><Link href={text("about.perspective.cta.destination")} className="text-link">{text("about.perspective.cta.label")}</Link></div></div></section><section className="case-section dark"><div className="about-wrap"><p className="eyebrow">{text("about.approach.eyebrow")}</p><div className="approach-stages">{approachKeys.map(k=>[text(`about.approach.${k}.heading`),text(`about.approach.${k}.description`)]).map(([title,text],i)=><div key={title}><span className="eyebrow">0{i+1}</span><h2>{title}</h2><p>{text}</p></div>)}</div></div></section><section className="case-section"><div className="about-wrap"><p className="eyebrow">{text("about.capabilities.eyebrow")}</p>{capabilities.map(([heading,...items],i)=><div className="capability-row" key={heading}><span className="eyebrow">0{i+1}</span><h2>{heading}</h2><p>{items.join(' / ')}</p></div>)}</div></section><TestimonialSlider eyebrow={text("about.testimonials.eyebrow")} testimonials={testimonials}/><ClientLogoWall clients={clientLogos} eyebrow={text("about.selected_clients.eyebrow")}/></div>}
