'use client';
import {useEffect,useState,useRef} from 'react';
import Link from '../../components/SiteLink';
import AdminNav from '../admin-nav';
import type {Preview} from '../../../lib/content-csv';
import type {Entry} from '../../../lib/content-registry';
type ApiResult=Preview&{revision:number;canRestore:boolean;entries:Entry[];changed:number};
async function call(body?:unknown):Promise<ApiResult>{const r=await fetch('/api/studio/content',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);if(!r.ok){let msg=await r.text();try{msg=JSON.parse(msg).error||msg}catch{}throw Error(msg)}return r.json() as Promise<ApiResult>}
export default function ContentManager(){
 const [state,setState]=useState<{revision:number;canRestore:boolean;entries:Entry[]}|null>(null),[csv,setCsv]=useState(''),[filename,setFilename]=useState(''),[preview,setPreview]=useState<(Preview&{revision:number})|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[restore,setRestore]=useState(false);const input=useRef<HTMLInputElement>(null);
 async function refresh(){setState(await call())}useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 return <section className="wrap studio"><div className="studio-heading"><div><p className="eyebrow">— Private workspace</p><h1>Content <em>/ CSV.</em></h1></div><Link className="text-link" href="/">View portfolio ↗</Link></div><AdminNav active="content"/>
 <p className="studio-intro">Export current copy, edit the value column, then review exactly what will change before applying it.</p>
 {error&&<p role="alert" className="status-banner error-banner">{error}</p>}{notice&&<p role="status" className="status-banner">{notice}</p>}
 <div className="content-actions"><a className="button" href="/api/studio/content?format=csv" download>Export current CSV ↓</a><button className="button secondary" disabled={busy} onClick={()=>input.current?.click()}>Import CSV ↑</button><button className="text-button" disabled={busy||!state?.canRestore} onClick={()=>setRestore(true)}>Restore previous content</button></div>
 <input hidden ref={input} type="file" accept=".csv,text/csv" aria-label="Import content CSV" onChange={e=>{const f=e.target.files?.[0];setPreview(null);setCsv('');setFilename('');if(f)void action(async()=>{if(f.size>1500000)throw Error('Choose a CSV smaller than 1.5 MB.');const text=await f.text();setCsv(text);setFilename(f.name);setPreview(await call({action:'preview',csv:text}));});if(input.current)input.current.value=''}}/>
 <details className="content-help"><summary>How to edit safely</summary><p>The columns are content_id, page, section, field, type, value. Keep content_id unchanged; it determines the destination. Page, section, field, and type are guides only. Row order does not matter. You may import just the rows you edited; omitted rows stay unchanged.</p><p>Use one item per line for lists, true / false for switches, and whole numbers for ordering. Rich text supports *italic*, **bold**, and line breaks; HTML is never executed. Links must point to existing portfolio routes. Project URLs and permanent keys stay fixed.</p><p>Shared titles and summaries are edited once in the project’s Opening fields and appear wherever that project is featured. Use Media Studio for images and videos. Featured order changes the sequence while keeping each project’s layout. Unpublished projects disappear from public navigation.</p><p>Spreadsheet formula protection may add a leading apostrophe to a value. Leave it in place; importing restores the original text. Save as UTF-8 comma-separated CSV from Excel or Google Sheets.</p><p>Each successful copy change saves one restore point, including changes to contact details. Resolve all unknown IDs and invalid rows before applying. Nothing is saved during preview.</p></details>
 {restore&&<div className="delete-confirm"><h2>Restore the previous content state?</h2><p>This restores copy, project publishing settings, and contact details from before the most recent save. Media files and assignments are untouched.</p><button disabled={busy} className="button" onClick={()=>action(async()=>{await call({action:'restore',revision:state?.revision});setRestore(false);setPreview(null);await refresh();setNotice('Previous content restored. Refresh the portfolio to see it.')})}>Restore content</button><button className="text-button" onClick={()=>setRestore(false)}>Cancel</button></div>}
 {preview&&<section className="import-preview"><div className="library-heading"><h2>Review import</h2><span>{filename}</span></div><div className="import-counts" aria-live="polite"><strong>{preview.changes.length} changes</strong><span>{preview.unchanged} unchanged</span><span>{preview.recognized} recognized</span><span>{preview.unknown.length} unknown IDs</span><span>{preview.invalid.length} invalid</span><span>{preview.missingRequired.length} missing required</span></div>
 {preview.error&&<p className="status-banner error-banner">{preview.error}</p>}{[...preview.unknown.map(e=>({...e,message:'Unknown content ID — no field will be created.'})),...preview.invalid,...preview.missingRequired].map((e,i)=><p className="csv-error" key={i}>Row {e.row||'—'} · {e.id||'(empty ID)'}: {e.message}</p>)}
 {preview.changes.map(c=><article className="copy-change" key={c.id}><h3>{c.location}</h3><small>{c.id} · {c.type}</small><div className="before-after"><div><p className="eyebrow">Before</p><p>{c.before||'(empty)'}</p></div><div><p className="eyebrow">After →</p><p>{c.after||'(empty)'}</p></div></div></article>)}
 {!preview.changes.length&&!preview.error&&!preview.invalid.length&&!preview.unknown.length&&!preview.missingRequired.length&&<p className="status-banner">No content changes. This CSV matches the current site.</p>}
 <div className="content-actions"><button className="button" disabled={busy||!preview.canApply} onClick={()=>action(async()=>{const r=await call({action:'apply',csv,revision:preview.revision});setPreview(null);await refresh();setNotice(`${r.changed} field${r.changed===1?'':'s'} updated. A restore point was saved. Refresh the portfolio to see the change.`)})}>Apply {preview.changes.length} changes</button><button className="text-button" disabled={busy} onClick={()=>action(async()=>setPreview(await call({action:'preview',csv})))}>Refresh preview</button><button className="text-button" onClick={()=>setPreview(null)}>Discard preview</button></div></section>}
 <section className="content-summary"><h2>One location for every piece of copy.</h2><p>{state?state.entries.filter(e=>e.editable&&!e.slot).length:'…'} editable fields. Find their page, section, permanent key, and current status in the <Link href="/studio/map">Site Map ↗</Link>.</p></section>
 </section>
}
