import {cache} from 'react';
import {db} from './storage';
import {contentValue,resolveProjects,type ContentValues} from './content-registry';
import {categoryKeys} from './projects';
export type ContentState={revision:number;values:ContentValues;canRestore:boolean};
export async function readContentState():Promise<ContentState>{const d=await db();const row=await d.prepare('SELECT revision,values_json,previous_json FROM content_state WHERE id=1').first<{revision:number;values_json:string;previous_json:string|null}>();let values:ContentValues={};try{values=JSON.parse(row?.values_json||'{}')}catch{}return {revision:row?.revision||0,values,canRestore:!!row?.previous_json}}
export const getContent=cache(async()=>{const state=await readContentState();const all=resolveProjects(state.values);const projects=all.filter(p=>p.published).sort((a,b)=>a.index_order-b.index_order);return {...state,allProjects:all,projects,featured:projects.filter(p=>p.featured).sort((a,b)=>a.featured_order-b.featured_order),categories:categoryKeys.map(k=>contentValue(`global.categories.${k}.label`,state.values)),text:(id:string)=>contentValue(id,state.values)}});
export async function saveContent(values:ContentValues,revision:number){const d=await db();const r=await d.prepare('UPDATE content_state SET previous_json=values_json,values_json=?,revision=revision+1,updated_at=? WHERE id=1 AND revision=?').bind(JSON.stringify(values),new Date().toISOString(),revision).run();if(!r.meta.changes)throw new Response('Content changed since your preview. Preview the import again before applying.',{status:409})}
export async function restoreContent(revision:number){const d=await db();const r=await d.prepare('UPDATE content_state SET values_json=previous_json,previous_json=NULL,revision=revision+1,updated_at=? WHERE id=1 AND revision=? AND previous_json IS NOT NULL').bind(new Date().toISOString(),revision).run();if(!r.meta.changes)throw new Response('The restore point changed or is no longer available. Refresh Content.',{status:409})}
