import {registry,registryById,contentValue,validateValue,type ContentValues} from './content-registry';
export const csvColumns=['content_id','page','section','field','type','value'];
// Spreadsheet formula protection is reversible, including literal leading apostrophes.
const protect=(s:string)=>/^[\s]*[=+\-@]|^[\t\r']/.test(s)?"'"+s:s;
const unprotect=(s:string)=>s.startsWith("'")&&/^[\s]*[=+\-@]|^[\t\r']/.test(s.slice(1))?s.slice(1):s;
export function exportCsv(values:ContentValues){const rows=[csvColumns,...registry.filter(e=>e.editable&&!e.slot).map(e=>[e.id,e.page,e.section,e.field,e.type,contentValue(e.id,values)])];return '\ufeff'+rows.map(row=>row.map(s=>'"'+protect(s).replace(/"/g,'""')+'"').join(',')).join('\r\n')+'\r\n'}
export function parseCsv(input:string){if(input.length>1500000)throw Error('Choose a CSV smaller than 1.5 MB.');const text=input.replace(/^\ufeff/,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n');const rows:string[][]=[];let row:string[]=[],cell='',quoted=false,closed=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++}else{quoted=false;closed=true}}else cell+=c;continue}if(c===','||c==='\n'){row.push(unprotect(cell));cell='';closed=false;if(c==='\n'){if(row.some(v=>v!==''))rows.push(row);row=[]}continue}if(closed)throw Error('Unexpected text after a closing quote. Export a fresh comma-separated CSV.');if(c==='"'){if(cell)throw Error('Unexpected quote in an unquoted cell.');quoted=true}else cell+=c;if(rows.length>5000)throw Error('Use 5,000 rows or fewer.')}if(quoted)throw Error('A quoted cell is not closed.');if(cell||row.length){row.push(unprotect(cell));rows.push(row)}return rows}
export type Change={id:string;location:string;type:string;before:string;after:string};
export type Preview={changes:Change[];unchanged:number;recognized:number;unknown:{row:number;id:string}[];invalid:{row:number;id:string;message:string}[];missingRequired:{row:number;id:string;message:string}[];error?:string;canApply:boolean};
export function previewCsv(csv:string,values:ContentValues):Preview{const r:Preview={changes:[],unchanged:0,recognized:0,unknown:[],invalid:[],missingRequired:[],canApply:false};try{const rows=parseCsv(csv);const header=rows.shift();if(!header||csvColumns.some(k=>!header.includes(k))||new Set(header).size!==header.length)throw Error('Required columns: '+csvColumns.join(', '));const idCol=header.indexOf('content_id'),valueCol=header.indexOf('value');const seen=new Set<string>();for(const [i,row] of rows.entries()){const id=(row[idCol]||'').trim(),e=registryById.get(id);if(row.length!==header.length){r.invalid.push({row:i+2,id,message:'Column count does not match the header.'});continue}if(seen.has(id)){r.invalid.push({row:i+2,id,message:'Duplicate content ID; each field may appear once.'});continue}seen.add(id);if(!e){r.unknown.push({row:i+2,id});continue}if(!e.editable||e.slot){r.invalid.push({row:i+2,id,message:e.slot?'Assign media in Media Studio.':'Shared copy is edited at its original project field.'});continue}r.recognized++;const value=row[valueCol];const problem=validateValue(e,value);if(problem){(e.required&&!value.trim()?r.missingRequired:r.invalid).push({row:i+2,id,message:problem});continue}const before=contentValue(id,values);if(before===value)r.unchanged++;else r.changes.push({id,location:e.location,type:e.type,before,after:value})}
 // Reject links into projects unpublished by this same import.
 const next={...values,...Object.fromEntries(r.changes.map(c=>[c.id,c.after]))};const names=registry.filter(e=>e.id.startsWith('global.categories.')).map(e=>contentValue(e.id,next).trim());if(new Set(names).size!==names.length||names.includes('All'))r.invalid.push({row:0,id:'global.categories',message:'Category labels must be unique and may not be All.'});for(const e of registry.filter(e=>e.type==='link'&&!e.slot)){const dest=contentValue(e.id,next).split(/[?#]/)[0];const p=registry.find(e=>e.id.endsWith('.published')&&e.route===dest);if(p&&contentValue(p.id,next)==='false')r.invalid.push({row:0,id:e.id,message:'This link points to a project marked unpublished.'})}
 r.canApply=r.changes.length>0&&!r.unknown.length&&!r.invalid.length&&!r.missingRequired.length;
 }catch(e){r.error=e instanceof Error?e.message:'Invalid CSV.'}return r}
