'use client';
import {useEffect,useState} from 'react';
import Link from '../../components/SiteLink';
import AdminNav from '../admin-nav';
import type {Entry} from '../../../lib/content-registry';
import type {Project} from '../../../lib/projects';
export default function ContentMap({projects}:{projects:Pick<Project,'title'|'slug'|'content_id'>[]}){const [entries,setEntries]=useState<Entry[]>([]),[error,setError]=useState(''),[filter,setFilter]=useState('All'),[search,setSearch]=useState('');useEffect(()=>{fetch('/api/studio/content').then(async r=>{if(!r.ok)throw Error('Could not load the Content Map. Refresh to try again.');setEntries(((await r.json()) as {entries:Entry[]}).entries)}).catch(e=>setError(e.message))},[]);
 const pages=['Site-wide','Homepage','Work / Index','About','Contact',...projects.map(p=>p.title)];const visible=(e:Entry)=>(filter==='All'||filter==='Needs content'&&e.status!=='COMPLETE'||filter==='Inactive'&&!e.active)&&(e.location+' '+e.value+' '+e.id).toLowerCase().includes(search.toLowerCase());
 return <section className="wrap studio"><div className="studio-heading"><div><p className="eyebrow">— Private workspace</p><h1>Site <em>map.</em></h1></div><Link className="text-link" href="/">View portfolio ↗</Link></div><AdminNav active="map"/><p className="studio-intro">Find each page, its copy, and its media positions. Complete means populated, not editorial approval. Optional empty fields are marked missing; the public site hides them safely.</p><div className="map-filters"><label>Find a location<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Project, section, or content key…"/></label><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Needs content','Inactive'].map(s=><option key={s}>{s}</option>)}</select></label></div>{error&&<p role="alert">{error}</p>}{!entries.length&&!error&&<p>Loading the content registry…</p>}
 {pages.map(page=>{const list=entries.filter(e=>e.page===page&&visible(e));if(!list.length)return null;const p=projects.find(p=>p.title===page);return <section key={page} className="map-page"><div className="library-heading"><h2>{page}</h2><Link href={p?`/work/${p.slug}`:list[0].route.split('#')[0]} target="_blank">View page ↗</Link></div>{p&&<p className="map-key">Project key: {p.content_id} · Route: /work/{p.slug}</p>}{[...new Set(list.map(e=>e.section))].map(section=>{const rows=list.filter(e=>e.section===section);const count=(state:string)=>rows.filter(e=>e.status===state).length;return <details className="map-section" key={section}><summary><strong>{section}</strong><span>{count('COMPLETE')} complete · {count('PLACEHOLDER')} placeholder · {count('MISSING')} missing</span></summary>{rows.map(e=><article key={e.id} className="map-entry"><div><strong>{e.field}</strong><span className={`content-status status-${e.status?.toLowerCase()}`}>{e.status}</span>{!e.active&&<span className="content-status">Inactive</span>}<p>{e.type.toUpperCase()} · {e.required?'Required':'Optional'}{e.sourceId?' · Shared copy':''}</p><small>{e.id}</small>{e.note&&<p>{e.note}</p>}{!e.slot&&<p className="map-copy">{e.value||'(empty)'}</p>}</div><div>{e.slot?<Link href={`/studio?page=${encodeURIComponent(e.page==='Homepage'?'home':e.page==='Work / Index'?'work':p?.slug||'home')}&slot=${encodeURIComponent(e.id)}`}>Assign media ↗</Link>:<Link href="/studio/content">{e.sourceId?'Edit shared copy':'Edit via CSV'} ↗</Link>}<Link href={e.route} target="_blank">View location ↗</Link></div></article>)}</details>})}</section>})}
 <section className="content-summary"><h2>Navigation notes</h2><p>Project cards and previous / next links follow the published project list. Related-project links appear when related project keys are supplied. Hidden and unpublished projects are excluded. The homepage count and category links follow the same content.</p><p>Contact email and LinkedIn actions are intentionally inactive while their fields are empty. No résumé or experience section has been added to the existing design. The private administration pages are Media Studio, Content / CSV, and Site Map.</p></section></section>
}
